'use client';

import { FormEvent, useState } from 'react';
import LayoutShell from '../components/LayoutShell';

type Tracking={order_number:string;status:string;carrier?:string;tracking_number?:string;tracking_url?:string;created_at:string;shipped_at?:string};
const labels:Record<string,string>={new:'Commande reçue',preparing:'En préparation',ready:'Prête à être expédiée',shipped:'Expédiée',cancelled:'Annulée'};

export default function OrderTrackingPage(){
 const [orderNumber,setOrderNumber]=useState('');
 const [email,setEmail]=useState('');
 const [order,setOrder]=useState<Tracking|null>(null);
 const [status,setStatus]=useState('');
 const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setStatus('Recherche de ta commande…');setOrder(null);try{const r=await fetch('/api/comentre/order-track.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderNumber:orderNumber.trim(),email:email.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error==='order_not_found'?'Commande introuvable. Vérifie le numéro et l’adresse email.':d.error||'Impossible de récupérer la commande.');setOrder(d.order);setStatus('')}catch(err){setStatus((err as Error).message)}finally{setLoading(false)}}
 return <LayoutShell><main className="tracking"><style>{css}</style><section className="hero"><p>Suivi de commande</p><h1>Où en est ta commande ?</h1><span>Entre ton numéro de commande et l’adresse email utilisée lors de l’achat.</span></section><form onSubmit={submit}><label>Numéro de commande<input value={orderNumber} onChange={e=>setOrderNumber(e.target.value)} placeholder="PAP-260915-ABC123" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="toi@exemple.fr" required/></label><button disabled={loading}>{loading?'Recherche…':'Voir mon suivi'}</button></form>{status&&<div className="message">{status}</div>}{order&&<section className="result"><small>{order.order_number}</small><h2>{labels[order.status]||order.status}</h2><div className="timeline"><div className="done">Commande reçue</div><div className={['preparing','ready','shipped'].includes(order.status)?'done':''}>En préparation</div><div className={['ready','shipped'].includes(order.status)?'done':''}>Prête</div><div className={order.status==='shipped'?'done':''}>Expédiée</div></div>{order.status==='shipped'&&<div className="parcel"><p><b>{order.carrier||'Transporteur'}</b>{order.tracking_number&&<> · {order.tracking_number}</>}</p>{order.tracking_url&&<a href={order.tracking_url} target="_blank" rel="noreferrer">Suivre le colis chez le transporteur →</a>}</div>}<p className="privacy">Pour ta sécurité, aucune adresse postale n’est affichée sur cette page.</p></section>}</main></LayoutShell>
}

const css=String.raw`*{box-sizing:border-box}.tracking{min-height:70vh;background:#fff8f1;color:#171b2a;padding:4rem 1.2rem}.hero,.tracking form,.message,.result{width:min(760px,100%);margin-left:auto;margin-right:auto}.hero{text-align:center;margin-bottom:2rem}.hero>p{font:900 .72rem Comfortaa,sans-serif;text-transform:uppercase;letter-spacing:.12em;color:#ff7168}.hero h1,.result h2{font-family:'Patrick Hand',cursive}.hero h1{font-size:clamp(2.8rem,7vw,4.5rem);line-height:.95;margin:.35rem 0}.hero span{display:block;font:600 .85rem/1.7 Comfortaa,sans-serif;color:#6b7280}.tracking form{background:#fff;padding:1.25rem;border-radius:1.5rem;box-shadow:0 16px 38px rgba(48,30,18,.06);display:grid;grid-template-columns:1fr 1fr auto;gap:.7rem;align-items:end}.tracking label{display:grid;gap:.35rem;font:900 .68rem Comfortaa,sans-serif}.tracking input{border:1px solid #e5ddd6;border-radius:.85rem;padding:.8rem;font:600 .8rem Comfortaa,sans-serif;background:#fffdfa}.tracking button{border:0;border-radius:999px;padding:.85rem 1rem;background:#171b2a;color:#fff;font:900 .72rem Comfortaa,sans-serif;cursor:pointer}.message{margin-top:1rem;background:#fff0ee;padding:.85rem 1rem;border-radius:1rem;font:700 .75rem Comfortaa,sans-serif}.result{margin-top:1rem;background:#fff;padding:1.5rem;border-radius:1.5rem;box-shadow:0 16px 38px rgba(48,30,18,.06)}.result small{font:900 .65rem Comfortaa,sans-serif;color:#ff7168}.result h2{font-size:2.5rem;margin:.2rem 0 1rem}.timeline{display:grid;grid-template-columns:repeat(4,1fr);gap:.4rem}.timeline div{background:#f1ece8;border-radius:999px;padding:.65rem .55rem;text-align:center;font:800 .64rem Comfortaa,sans-serif;color:#8a8d94}.timeline .done{background:#dff7f2;color:#265c50}.parcel{margin-top:1rem;padding:1rem;background:#fff8f1;border-radius:1rem;font:700 .75rem Comfortaa,sans-serif}.parcel p{margin:0 0 .4rem}.parcel a{font-weight:900}.privacy{margin-top:1rem;color:#7a7f87;font:600 .68rem/1.6 Comfortaa,sans-serif}@media(max-width:720px){.tracking{padding:2.5rem .9rem}.tracking form{grid-template-columns:1fr}.timeline{grid-template-columns:1fr 1fr}}`;
