'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import initialSeasonal from '../../../content/seasonal.json';

type Seasonal=typeof initialSeasonal;
const OWNER='vartcom38-collab';const REPO='comentre-nous-site';const BRANCH='main';const PATH='content/seasonal.json';
function encodeBase64(value:string){return btoa(unescape(encodeURIComponent(value)))}
async function github(path:string,token:string,init?:RequestInit){const response=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/${path}`,{...init,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${token}`,...(init?.headers||{})}});if(!response.ok)throw new Error(`${response.status} ${response.statusText} — ${await response.text()}`);return response.json()}

export default function SeasonalAdminPage(){
 const [token,setToken]=useState('');const [value,setValue]=useState<Seasonal>(initialSeasonal);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{setToken(window.sessionStorage.getItem('comentre_admin_github_token')||window.localStorage.getItem('comentre_admin_github_token')||'')},[]);
 async function save(){if(!token)return setStatus('Reconnecte GitHub depuis l’admin général.');setBusy(true);setStatus('Enregistrement…');try{const current=await github(`contents/${PATH}?ref=${BRANCH}`,token);await github(`contents/${PATH}`,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Admin: update seasonal ambiance',content:encodeBase64(`${JSON.stringify(value,null,2)}\n`),sha:current.sha,branch:BRANCH})});setStatus('Ambiance enregistrée. Le site va se redéployer automatiquement.');}catch(error){setStatus(`Erreur : ${(error as Error).message}`)}finally{setBusy(false)}}
 return <main className="season-admin"><style>{css}</style><header><div><Link href="/admin/">← Admin</Link><p>Personnalisation</p><h1>Ambiance du site</h1><span>Une couche décorative posée sur le site, sans changer ses couleurs, ses textes ni sa mise en page.</span></div><button className="save" onClick={save} disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}</button></header>{status&&<div className="status">{status}</div>}
 <section className="panel"><div className="panel-head"><div><small>Activation</small><h2>Décoration saisonnière</h2><p>Tu peux couper toute la décoration en un clic.</p></div><label className="switch"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/><span>{value.enabled?'Activée':'Désactivée'}</span></label></div>
 <div className="grid"><label>Ambiance<select value={value.theme} onChange={e=>setValue({...value,theme:e.target.value as Seasonal['theme']})}><option value="none">Aucune</option><option value="halloween">Halloween — test</option></select></label><label>Intensité<select value={value.intensity} onChange={e=>setValue({...value,intensity:e.target.value as Seasonal['intensity']})}><option value="light">Très léger</option><option value="festive">Plus présent</option></select></label></div>
 <div className="note"><b>Test actuel</b><span>On utilise vos éléments dessinés existants uniquement pour valider les placements. Les vrais éléments Halloween seront dessinés ensuite dans votre univers, pas en vectoriel générique.</span></div></section>
 <section className="preview"><small>Aperçu du principe</small><h2>Le site ne change pas.</h2><p>Les décors viennent simplement se poser sur les bords et entre certains blocs, comme des petits éléments ajoutés par-dessus.</p><div className="peek one">petit personnage</div><div className="peek two">petit personnage</div></section>
 <footer><button onClick={save} disabled={busy}>Enregistrer l’ambiance</button><Link href="/" target="_blank">Voir le site →</Link></footer></main>
}
const css=String.raw`*{box-sizing:border-box}.season-admin{min-height:100vh;background:#fff8f1;color:#171b2a;padding:28px clamp(16px,4vw,56px) 70px;font-family:Comfortaa,system-ui,sans-serif}.season-admin header,.panel,.preview,.status,.season-admin footer{max-width:980px;margin-left:auto;margin-right:auto}.season-admin header{display:flex;justify-content:space-between;align-items:end;gap:20px}.season-admin header a{font-size:12px;font-weight:900;text-decoration:none;color:#171b2a}.season-admin header p{margin:14px 0 4px;color:#ff7168;text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:900}.season-admin h1,.season-admin h2{font-family:'Patrick Hand',cursive}.season-admin h1{font-size:56px;line-height:.95;margin:0}.season-admin header span{display:block;margin-top:8px;color:#6d7280;font-size:12px;line-height:1.6}.season-admin button{border:0;border-radius:999px;padding:12px 17px;font:900 12px Comfortaa,system-ui,sans-serif;cursor:pointer}.save,.season-admin footer button{background:#171b2a;color:#fff}.panel,.preview{margin-top:20px;background:#fff;border-radius:24px;padding:24px;box-shadow:0 14px 40px rgba(50,35,25,.07)}.panel-head{display:flex;justify-content:space-between;gap:18px;align-items:start}.panel small,.preview small{color:#ff7168;text-transform:uppercase;letter-spacing:.1em;font-size:10px;font-weight:900}.panel h2,.preview h2{font-size:34px;margin:4px 0 6px}.panel p,.preview p{font-size:12px;line-height:1.7;color:#6d7280}.switch{display:flex;align-items:center;gap:9px;font-size:12px;font-weight:900}.switch input{width:18px;height:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.grid label{display:grid;gap:7px;font-size:12px;font-weight:900}.grid select{border:1px solid #e5ddd6;border-radius:14px;padding:12px;background:#fffdfa;font:700 13px Comfortaa,system-ui,sans-serif}.note{margin-top:18px;background:#fff3ea;border-radius:16px;padding:14px;display:grid;gap:5px}.note b{font-size:12px}.note span{font-size:11px;line-height:1.6;color:#6e5550}.preview{position:relative;overflow:hidden;min-height:240px}.preview p{max-width:620px}.peek{position:absolute;border:2px dashed #d9cdc4;border-radius:50%;width:110px;height:110px;display:grid;place-items:center;font-size:10px;color:#9b8c82;background:#fffaf6}.peek.one{right:-28px;top:24px;transform:rotate(-7deg)}.peek.two{left:-28px;bottom:-28px;transform:rotate(8deg)}.status{margin-top:14px;background:#dff7f2;border-radius:14px;padding:12px 14px;font-size:12px;font-weight:800}.season-admin footer{display:flex;gap:10px;align-items:center;margin-top:16px}.season-admin footer a{text-decoration:none;background:#fff;border-radius:999px;padding:11px 15px;color:#171b2a;font-size:11px;font-weight:900}@media(max-width:700px){.season-admin{padding:18px 12px 50px}.season-admin header{align-items:flex-start;flex-direction:column}.season-admin h1{font-size:44px}.grid{grid-template-columns:1fr}.panel-head{flex-direction:column}}`;
