'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

type StripeState={connected:boolean;accountId:string;label:string;livemode:boolean;connectReady:boolean};
type State={stripe:StripeState;mondialRelay:{connected:boolean;enseigne:string}};
const empty:State={stripe:{connected:false,accountId:'',label:'',livemode:false,connectReady:false},mondialRelay:{connected:false,enseigne:''}};

export default function ConnectionsPage(){
 const[token,setToken]=useState('');const[state,setState]=useState<State>(empty);const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);const[enseigne,setEnseigne]=useState('');const[mrKey,setMrKey]=useState('');
 useEffect(()=>{const saved=window.sessionStorage.getItem('comentre_admin_github_token')||window.localStorage.getItem('comentre_admin_github_token')||'';setToken(saved);const params=new URLSearchParams(window.location.search);const stripe=params.get('stripe');if(stripe==='connected')setStatus('Stripe d’Aurélie est maintenant connecté.');else if(stripe==='cancelled')setStatus('Connexion Stripe annulée.');else if(stripe==='expired')setStatus('Le lien Stripe a expiré. Relance simplement la connexion.');else if(stripe==='setup')setStatus('La connexion Stripe doit encore être activée côté plateforme.');else if(stripe==='failed'||stripe==='invalid')setStatus('La connexion Stripe n’a pas abouti.');if(saved)load(saved)},[]);
 async function api(body?:unknown,t=token){const response=await fetch('/api/comentre/papeterie-integrations.php',{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Admin-Github-Token':t},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Erreur');return data}
 async function load(t=token){setBusy(true);try{const data=await api(undefined,t);setState({stripe:data.stripe,mondialRelay:data.mondialRelay});setEnseigne(data.mondialRelay.enseigne||'');}catch(e){setStatus(`Erreur : ${(e as Error).message}`)}finally{setBusy(false)}}
 async function connectStripe(){if(!token)return setStatus('Reconnecte-toi depuis l’admin général.');setBusy(true);setStatus('Ouverture de Stripe…');try{const response=await fetch('/api/comentre/papeterie-stripe-connect.php',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Github-Token':token}});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Erreur');window.location.href=data.authorizeUrl}catch(e){const message=(e as Error).message;setStatus(message==='stripe_connect_not_configured'?'La connexion Stripe est prête côté admin, mais doit encore être activée une fois côté plateforme.':`Stripe : ${message}`);setBusy(false)}}
 async function disconnectStripe(){if(!confirm('Déconnecter le compte Stripe d’Aurélie ?'))return;setBusy(true);try{await api({action:'disconnect_stripe'});setState(s=>({...s,stripe:empty.stripe}));setStatus('Stripe déconnecté.')}catch(e){setStatus(`Erreur : ${(e as Error).message}`)}finally{setBusy(false)}}
 async function saveMondial(){if(!enseigne.trim()||!mrKey.trim())return setStatus('Renseigne l’enseigne et la clé privée Mondial Relay.');setBusy(true);setStatus('Connexion à Mondial Relay…');try{const data=await api({action:'save_mondialrelay',enseigne:enseigne.trim(),privateKey:mrKey.trim()});setState(s=>({...s,mondialRelay:data.mondialRelay}));setMrKey('');setStatus('Mondial Relay est configuré pour la Papeterie.')}catch(e){setStatus(`Mondial Relay : ${(e as Error).message}`)}finally{setBusy(false)}}
 async function disconnectMondial(){if(!confirm('Déconnecter Mondial Relay ?'))return;setBusy(true);try{await api({action:'disconnect_mondialrelay'});setState(s=>({...s,mondialRelay:empty.mondialRelay}));setMrKey('');setStatus('Mondial Relay déconnecté.')}catch(e){setStatus(`Erreur : ${(e as Error).message}`)}finally{setBusy(false)}}
 return <main className="connections"><style>{css}</style><header><div><Link href="/admin/papeterie/">← L’atelier d’Aurélie</Link><p>Papeterie uniquement</p><h1>Paiements & livraison</h1><span>Aurélie gère ici ses connexions sans passer par Infomaniak ou GitHub. Les autres univers gardent leurs propres canaux Amazon / WooCommerce.</span></div></header>{status&&<div className="status">{status}</div>}
 <section className="card stripe-card"><div className="top"><div><small>Paiement</small><h2>Stripe d’Aurélie</h2><p>Tous les produits Papeterie reliés à Stripe utiliseront uniquement ce compte.</p></div><span className={state.stripe.connected?'badge ok':'badge'}>{state.stripe.connected?'Connecté':'Non connecté'}</span></div>{state.stripe.connected?<><div className="connected"><b>{state.stripe.label||'Compte Stripe Aurélie'}</b><span>{state.stripe.accountId}</span><em>{state.stripe.livemode?'Paiements réels activés':'Mode test'}</em></div><div className="actions"><button className="danger" onClick={disconnectStripe} disabled={busy}>Changer / déconnecter le compte</button></div></>:<><div className="connect-box"><b>Connexion simple</b><p>Aucune clé API à copier. Aurélie clique, se connecte à Stripe, autorise Com’ entre nous puis revient ici automatiquement.</p><button onClick={connectStripe} disabled={busy}>{busy?'Ouverture…':'Se connecter avec Stripe'}</button></div>{!state.stripe.connectReady&&<p className="hint">Le bouton est installé. La plateforme Stripe Connect doit être activée une seule fois côté technique avant la première connexion d’Aurélie.</p>}</>}</section>
 <section className="card"><div className="top"><div><small>Expédition</small><h2>Mondial Relay</h2><p>Une fois configuré, Aurélie pourra gérer les Points Relais, expéditions, étiquettes et suivis depuis son espace.</p></div><span className={state.mondialRelay.connected?'badge ok':'badge'}>{state.mondialRelay.connected?'Configuré':'Non configuré'}</span></div><div className="grid"><label>Enseigne Mondial Relay<input value={enseigne} onChange={e=>setEnseigne(e.target.value.toUpperCase())} placeholder="Code enseigne"/></label><label>Clé privée<input type="password" autoComplete="off" value={mrKey} onChange={e=>setMrKey(e.target.value)} placeholder={state.mondialRelay.connected?'••••••••••':'Clé privée Mondial Relay'}/></label></div><p className="hint">Ces informations sont enregistrées côté serveur et ne sont pas visibles dans GitHub.</p><div className="actions"><button onClick={saveMondial} disabled={busy}>{state.mondialRelay.connected?'Mettre à jour':'Configurer Mondial Relay'}</button>{state.mondialRelay.connected&&<button className="danger" onClick={disconnectMondial} disabled={busy}>Déconnecter</button>}</div></section>
 <section className="next"><small>Règle Papeterie</small><h2>Papeterie = compte d’Aurélie</h2><p>Le paiement des produits Papeterie sera isolé des autres univers. Une fiche Papeterie ne devra jamais envoyer un paiement vers Amazon, WooCommerce ou un autre compte Stripe.</p></section></main>
}
const css=String.raw`*{box-sizing:border-box}.connections{min-height:100vh;background:#fff8f3;color:#171b2a;padding:32px clamp(16px,4vw,56px) 70px;font-family:Comfortaa,system-ui,sans-serif}.connections>header,.card,.status,.next{max-width:900px;margin-left:auto;margin-right:auto}.connections header a{color:#171b2a;text-decoration:none;font-size:12px;font-weight:900}.connections header p{margin:16px 0 5px;color:#d96b7d;text-transform:uppercase;letter-spacing:.12em;font-size:10px;font-weight:900}.connections h1,.connections h2{font-family:'Patrick Hand',cursive}.connections h1{font-size:54px;line-height:1;margin:0}.connections header span{display:block;margin-top:8px;color:#777;font-size:12px;line-height:1.6}.status{margin-top:18px;padding:12px 14px;border-radius:14px;background:#e2f5ef;font-size:12px;font-weight:800}.card,.next{margin-top:18px;background:#fff;border-radius:24px;padding:24px;box-shadow:0 14px 38px rgba(55,35,28,.07)}.stripe-card{border:1px solid #eee4ff}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.card small,.next small{font-size:10px;color:#d96b7d;text-transform:uppercase;letter-spacing:.12em;font-weight:900}.card h2,.next h2{margin:4px 0 6px;font-size:34px}.card p,.next p{font-size:12px;line-height:1.7;color:#6f737d}.badge{padding:8px 10px;border-radius:999px;background:#f3ece7;font-size:10px;font-weight:900;white-space:nowrap}.badge.ok{background:#dff4e9;color:#1f6e4a}.connections label{display:grid;gap:7px;font-size:11px;font-weight:900;margin-top:15px}.connections input{border:1px solid #e6ddd6;border-radius:13px;padding:12px 13px;background:#fffdfa;font:700 12px Comfortaa,system-ui,sans-serif}.connections button{border:0;border-radius:999px;background:#171b2a;color:#fff;padding:11px 15px;font:900 11px Comfortaa,system-ui,sans-serif;cursor:pointer}.connections button:disabled{opacity:.5;cursor:wait}.danger{background:#fff0ee!important;color:#a84e4e!important}.hint{font-size:10px!important;color:#8b7b72!important}.connected{margin:16px 0;padding:16px;border-radius:15px;background:#f7fbf9;display:grid;gap:5px}.connected b{font-size:13px}.connected span,.connected em{font-size:11px;color:#6f737d;font-style:normal}.connect-box{margin-top:18px;padding:18px;border-radius:18px;background:#f7f1ff}.connect-box b{font-size:13px}.connect-box button{margin-top:8px;background:#635bff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.actions{display:flex;gap:10px;align-items:center;margin-top:14px}@media(max-width:700px){.connections{padding:20px 12px 50px}.connections h1{font-size:42px}.top{flex-direction:column}.grid{grid-template-columns:1fr}.actions{align-items:stretch;flex-direction:column}.connect-box button{width:100%}}`;
