'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import initialPodcast from '../../../content/podcast.json';

type PodcastContent=typeof initialPodcast;
type Episode=PodcastContent['episodes'][number];

const OWNER='vartcom38-collab';
const REPO='comentre-nous-site';
const BRANCH='main';
const PATH='content/podcast.json';

function encodeBase64(value:string){return btoa(unescape(encodeURIComponent(value)))}
function decodeBase64(value:string){return decodeURIComponent(escape(atob(value.replace(/\n/g,''))))}
async function github(path:string,token:string,init?:RequestInit){const response=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/${path}`,{...init,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${token}`,...(init?.headers||{})}});if(!response.ok)throw new Error(`${response.status} ${response.statusText} — ${await response.text()}`);return response.json()}
async function saveJson(value:unknown,token:string){const current=await github(`contents/${PATH}?ref=${BRANCH}`,token);return github(`contents/${PATH}`,token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Admin: update podcast',content:encodeBase64(`${JSON.stringify(value,null,2)}\n`),sha:current.sha,branch:BRANCH})})}
function blankEpisode(number:number):Episode{return{id:`episode-${Date.now()}`,number,title:'Nouvel épisode',description:'',published:false,date:'',duration:'',spotifyUrl:'',appleUrl:'',youtubeUrl:'',externalUrl:'',image:''}}

export default function PodcastAdmin(){
 const[token,setToken]=useState('');const[data,setData]=useState<PodcastContent>(initialPodcast);const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);const[selectedId,setSelectedId]=useState('');
 useEffect(()=>{const saved=window.sessionStorage.getItem('comentre_admin_github_token')||'';setToken(saved);if(saved)github(`contents/${PATH}?ref=${BRANCH}`,saved).then(file=>setData(JSON.parse(decodeBase64(file.content)))).catch(error=>setStatus(`Chargement impossible : ${error.message}`))},[]);
 const selected=useMemo(()=>data.episodes.find(e=>e.id===selectedId),[data,selectedId]);
 function updatePage(patch:Partial<PodcastContent['page']>){setData(c=>({...c,page:{...c.page,...patch}}))}
 function updateEpisode(id:string,patch:Partial<Episode>){setData(c=>({...c,episodes:c.episodes.map(e=>e.id===id?{...e,...patch}:e)}))}
 function addEpisode(){const number=(Math.max(0,...data.episodes.map(e=>e.number))+1);const episode=blankEpisode(number);setData(c=>({...c,episodes:[episode,...c.episodes]}));setSelectedId(episode.id)}
 function removeEpisode(id:string){if(!confirm('Supprimer cet épisode ?'))return;setData(c=>({...c,episodes:c.episodes.filter(e=>e.id!==id)}));if(selectedId===id)setSelectedId('')}
 async function save(){if(!token)return setStatus('Reconnecte GitHub depuis l’admin.');setBusy(true);setStatus('Enregistrement…');try{await saveJson(data,token);setStatus('Podcast enregistré. Le site va être redéployé.')}catch(error){setStatus(`Erreur : ${(error as Error).message}`)}finally{setBusy(false)}}
 return <main className="pod-admin"><style>{css}</style><header><div><Link href="/admin/">← Tableau de bord</Link><p>Podcast</p><h1>Gérer les épisodes</h1><span>Ajoute, prépare et publie les épisodes depuis ici.</span></div><button onClick={save} disabled={busy}>Enregistrer le podcast</button></header>{status&&<div className="status">{status}</div>}
 <section className="page-settings"><h2>Page podcast</h2><label>Petite accroche<input value={data.page.kicker} onChange={e=>updatePage({kicker:e.target.value})}/></label><label>Titre<input value={data.page.title} onChange={e=>updatePage({title:e.target.value})}/></label><label>Introduction<textarea rows={4} value={data.page.intro} onChange={e=>updatePage({intro:e.target.value})}/></label><label>Thèmes<textarea rows={3} value={data.page.themes} onChange={e=>updatePage({themes:e.target.value})}/></label></section>
 <div className="toolbar"><h2>Épisodes</h2><button onClick={addEpisode}>+ Ajouter un épisode</button></div>
 <section className="layout"><div className="episode-list">{[...data.episodes].sort((a,b)=>b.number-a.number).map(e=><button key={e.id} className={selectedId===e.id?'selected':''} onClick={()=>setSelectedId(e.id)}><span>{String(e.number).padStart(2,'0')}</span><div><b>{e.title}</b><small>{e.published?'Publié':'Brouillon'}{e.date?` · ${e.date}`:''}</small></div></button>)}</div>
 <div className="editor">{selected?<><div className="editor-head"><div><small>Épisode {String(selected.number).padStart(2,'0')}</small><h2>{selected.title}</h2></div><button className="danger" onClick={()=>removeEpisode(selected.id)}>Supprimer</button></div><div className="grid"><label>Numéro<input type="number" value={selected.number} onChange={e=>updateEpisode(selected.id,{number:Number(e.target.value)})}/></label><label>Date<input type="date" value={selected.date} onChange={e=>updateEpisode(selected.id,{date:e.target.value})}/></label><label className="wide">Titre<input value={selected.title} onChange={e=>updateEpisode(selected.id,{title:e.target.value})}/></label><label className="wide">Description<textarea rows={5} value={selected.description} onChange={e=>updateEpisode(selected.id,{description:e.target.value})}/></label><label>Durée<input value={selected.duration} placeholder="32 min" onChange={e=>updateEpisode(selected.id,{duration:e.target.value})}/></label><label>Image / couverture<input value={selected.image} placeholder="/uploads/..." onChange={e=>updateEpisode(selected.id,{image:e.target.value})}/></label><label className="wide">Lien Spotify<input value={selected.spotifyUrl} onChange={e=>updateEpisode(selected.id,{spotifyUrl:e.target.value})}/></label><label className="wide">Lien Apple Podcasts<input value={selected.appleUrl} onChange={e=>updateEpisode(selected.id,{appleUrl:e.target.value})}/></label><label className="wide">Lien YouTube<input value={selected.youtubeUrl} onChange={e=>updateEpisode(selected.id,{youtubeUrl:e.target.value})}/></label><label className="wide">Autre lien<input value={selected.externalUrl} onChange={e=>updateEpisode(selected.id,{externalUrl:e.target.value})}/></label></div><label className="publish-check"><input type="checkbox" checked={selected.published} onChange={e=>updateEpisode(selected.id,{published:e.target.checked})}/> Publier cet épisode sur le site</label></>:<div className="empty"><h3>Sélectionne un épisode</h3><p>Ou crée-en un nouveau pour commencer.</p></div>}</div></section><footer><button onClick={save} disabled={busy}>Enregistrer le podcast</button><Link href="/podcast">Voir la page podcast →</Link></footer></main>}

const css=`*{box-sizing:border-box}.pod-admin{min-height:100vh;background:#fff8f1;color:#111827;padding:28px clamp(16px,4vw,56px) 70px;font-family:Comfortaa,system-ui,sans-serif}.pod-admin>header{display:flex;justify-content:space-between;gap:24px;align-items:end;max-width:1400px;margin:auto}.pod-admin>header p{margin:16px 0 4px;color:#ff5d62;text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:900}.pod-admin h1{margin:0;font:700 clamp(40px,5vw,64px)/.95 'Patrick Hand',cursive}.pod-admin header span{display:block;margin-top:8px;color:#687083;font-size:13px}.pod-admin button{border:0;border-radius:999px;background:#171b2a;color:#fff;padding:11px 16px;font-weight:900;cursor:pointer}.status{max-width:1400px;margin:18px auto;background:#dff7f2;padding:12px 16px;border-radius:14px}.page-settings,.layout,.toolbar,.pod-admin footer{max-width:1400px;margin:18px auto}.page-settings{background:#fff;border-radius:24px;padding:22px}.page-settings h2,.toolbar h2,.editor h2{font:700 32px/1 'Patrick Hand',cursive}.page-settings label,.editor label{display:grid;gap:6px;font-size:12px;font-weight:900;margin-bottom:12px}.page-settings input,.page-settings textarea,.editor input,.editor textarea{border:1px solid #e4dad2;border-radius:12px;padding:11px 12px;background:#fffdf9;font:600 14px Comfortaa,system-ui,sans-serif}.toolbar{display:flex;justify-content:space-between;align-items:center}.layout{display:grid;grid-template-columns:340px 1fr;gap:16px}.episode-list{display:grid;gap:8px;align-content:start}.episode-list>button{border-radius:18px;background:#fff;color:#111827;padding:14px;text-align:left;display:flex;gap:12px;align-items:center}.episode-list>button.selected{outline:2px solid #171b2a}.episode-list>button>span{font:700 28px/1 'Patrick Hand',cursive}.episode-list div{display:grid;gap:4px}.episode-list small{color:#727887}.editor{background:#fff;border-radius:24px;padding:22px;min-height:360px}.editor-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.editor-head h2{margin:4px 0 16px}.danger{background:#fff0ef!important;color:#b42318!important}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.wide{grid-column:1/-1}.publish-check{display:flex!important;align-items:center;gap:8px;margin-top:8px}.publish-check input{width:auto}.empty{display:grid;place-items:center;text-align:center;min-height:300px}.pod-admin footer{display:flex;gap:14px;align-items:center}.pod-admin footer a{font-weight:900}@media(max-width:850px){.pod-admin>header{align-items:flex-start;flex-direction:column}.layout{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}`;
